name: Docker Build/Publish Image
on:
  push:
    branches: [main]
    tags: '*'
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Commit or Tag
        id: vars
        run: |
          tag="${GITHUB_SHA:0:8}"
          if [[ ${GITHUB_REF} == refs/tags* ]]; then
            tag=$(echo $GITHUB_REF | sed 's/refs\/tags\///g')
          fi
          echo "TAG=$tag" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: cboin/pigbot:latest,cboin/pigbot:${{ steps.vars.outputs.TAG }}
          cache-from: type=registry,ref=cboin/pigbot:buildcache
          cache-to: type=registry,ref=cboin/pigbot:buildcache,mode=max
      - name: Build and Push
        if: github.event_name == 'push' || startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: cboin/pigbot:latest,cboin/pigbot:${{ steps.vars.outputs.TAG }}
          cache-from: type=registry,ref=cboin/pigbot:buildcache
          cache-to: type=registry,ref=cboin/pigbot:buildcache,mode=max
