name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
      - uses: astral-sh/setup-uv@v6
      - name: Install requirements
        run: uv sync --extra dev
